server:
  port: 7000

spring:
  application:
    name: member

  redis:
    database: 0
    host: 188.131.147.130
    port: 6379
    password: 123456
    timeout: 50000ms
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1

    session:
      store-type: redis


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka5001.com:5001/eureka/,http://eureka5000.com:5000/eureka/

  # 心跳检测检测与续约时间
  # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
  instance:
    ###Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
    ####Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 2

    # 显示真实ip
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}