server:
  port: 8892
spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
  instance:
    prefer-ip-address: true
#zuul:
#  #（自定义路由映射）
#  prefix: /api（前缀）
#  routes: （设置路由）
#    order-service:（自定义）
#    path: /apigateway/order/**（自定义路径）
#    serviceId: model-order（对应的相关服务）
#  ignored-patterns: /*-service/** （统一上面的配置，其他入口忽略）
#  ignored-services: order-service（忽略整个服务，对外提供接口）