server:
  port: 8892
spring:
  application:
    name: gateway

  redis:
    database: 0
    host: 188.131.147.130
    port: 6379
    password: 123456
    timeout: 50000ms
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1

    session:
      store-type: redis

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka5001.com:5001/eureka/,http://eureka5000.com:5000/eureka/
  instance:
    # 显示真实ip
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#zuul:
#  #（自定义路由映射）
#  prefix: /api（前缀）
#  routes: （设置路由）
#    order-service:（自定义）
#    path: /apigateway/order/**（自定义路径）
#    serviceId: model-order（对应的相关服务）
#  ignored-patterns: /*-service/** （统一上面的配置，其他入口忽略）
#  ignored-services: order-service（忽略整个服务，对外提供接口）

zuul:
  #ignored-services: microservicecloud-dept
  #prefix: /atguigu
  ignored-services: "*"
  routes:
    mydept.serviceId: order
    mydept.path: /order/**
    mydept.sensitiveHeaders: "*"

ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 熔断超时时长：6000ms
